name: Generate test matrices pages

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to check out'
        default: 'main'
        required: false
        type: string
      pr_number:
        description: 'PR number'
        required: true
        type: number

jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout generation code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          path: exec
          sparse-checkout: |
            workflows/test_matrix_dashboard/

      - name: Check out baseline
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: baseline
          sparse-checkout: |
            old_ocp_data.json

      - name: Run extraction script
        run: |
          ls -1R ${GITHUB_WORKSPACE}/exec
          ls -1R ${GITHUB_WORKSPACE}/baseline
